std_msgs/Header header

string color
string name
string type
float32 confidence

float32 center_x
float32 center_y
float32 center_norm_x
float32 center_norm_y

float64 xyz_in_gimbal_x
float64 xyz_in_gimbal_y
float64 xyz_in_gimbal_z
float64 xyz_in_world_x
float64 xyz_in_world_y
float64 xyz_in_world_z

float64 ypr_in_gimbal_x
float64 ypr_in_gimbal_y
float64 ypr_in_gimbal_z
float64 ypr_in_world_x
float64 ypr_in_world_y
float64 ypr_in_world_z

float64 yaw_raw

float32 points_0_x
float32 points_0_y
float32 points_1_x
float32 points_1_y
float32 points_2_x
float32 points_2_y
float32 points_3_x
float32 points_3_y

float32 ratio
float32 side_ratio
float32 rectangular_error
